version: '3.3'

services:
   db:
     image: mvscharan9/spectrum_website:mysqlimg
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 5555
       MYSQL_DATABASE: spectrumdata
       MYSQL_USER: root
     expose:
        - "3306"
       
   webapi:
     depends_on:
       - db
     image: mvscharan9/spectrum_website:webimg 
     ports:
       - "8086:8080"
     restart: always